=== ronan-boue/scci/zeppelin/config/test/test-zeppelin-generic-schema-1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "object",
  "properties": {
    "specversion": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "time": {
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "source": {
      "type": "string"
    },
    "subject": {
      "type": "string"
    },
    "datacontenttype": {
      "type": "string"
    },
    "dataversion": {
      "type": "string"
    },
    "device_id": {
      "type": "string"
    },
    "data": {
      "type": "object",
      "properties": {
        "device": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "class": {
              "type": "string"
            },
            "protocol": {
              "type": "string"
            },
            "uuid": {
              "type": "string"
            },
            "id": {
              "type": "string"
            }
          },
          "required": [
            "name",
            "class",
            "protocol",
            "uuid",
            "id"
          ]
        },
        "values": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "value": {},
              "id": {
                "type": "string"
              },
              "address": {
                "type": "number"
              },
              "name": {
                "type": "string"
              },
              "description": {
                "type": "string"
              },
              "unit": {
                "type": "string"
              }
            },
            "required": [
              "value",
              "id",
              "address",
              "name",
              "description",
              "unit"
            ]
          }
        }
      },
      "required": [
        "device",
        "values"
      ]
    }
  },
  "required": [
    "specversion",
    "type",
    "time",
    "id",
    "source",
    "subject",
    "datacontenttype",
    "dataversion",
    "device_id",
    "data"
  ]
}

=== ronan-boue/scci/zeppelin/src/test/gen/message3.json
{
    "specversion": "1.0",
    "type": "ca.qc.hydro.iot.test.generic",
    "time": "2025-05-28T15:33:33Z",
    "id": "1d07944a-ee4b-453a-b81f-0774b8e4f647",
    "source": "test generic 3",
    "subject": "",
    "datacontenttype": "application/json; charset=utf-8",
    "dataversion": "1.0",
    "device_id": "ubuntu-edge-jfg",
    "data": {
        "device": {
            "name": "eGauge78294",
            "class": "EGaugeClient",
            "protocol": "modbus",
            "uuid": "6decfd46-7eab-4598-a916-01904aa2e093",
            "id": "ubuntu-edge-jfg"
        },
        "values": [
            {
                "value": 1717515957,
                "id": "LOCAL-TIME-EPOCH-SEC",
                "address": 30000,
                "name": "local timestamp (sec)",
                "description": "",
                "unit": "s"
            },
            {
                "value": 29.75,
                "id": "TEMPERATURE",
                "address": 30016,
                "name": "on-board temperature",
                "description": "",
                "unit": "Â°C"
            },
            {
                "value": "2205180276",
                "id": "SERIAL-NUMBER",
                "address": 30100,
                "name": "device serial number",
                "description": "",
                "unit": ""
            }
        ]
    }
}
